- name: Credentials file creation.
  hosts: localhost
  vars:
    SUBSCRIPTION_ID:(Input Subscription ID !)
    CLIENT_ID:(Input Client ID !)
    SECRET_ID:(Input Secret ID !)
    TENANT_ID:(Input Tenant ID !)
  tasks:
  - name: Creating Credentials file in the local host for Ansible's integration to the Azure account.
    copy:
      dest: "$HOME/.azure/credentials"
      content: |
        [default]
        subscription_id={{ SUBSCRIPTION_ID }}
        client_id={{ CLIENT_ID }}
        secret={{ SECRET_ID }}
        tenant={{ TENANT_ID }}